### ISSUE TITLE
Errors from other modules/classes aren't being raised

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-super_scaffolding#58]
I'm not entirely sure why this is happening so I want to look into this, but errors aren't being raised in methods from the `RoutesFileManipulator`, `FileManipulator`, etc. when we're running code in the Transformer.

## Example model
```
rails g model Project team:references title:string && \
bin/super-scaffold crud Project Team title:text_field --sidebar="ti.ti-world"
```

## Errors in the Transformer
The console will raise errors and stop the process if it's coming from directly within the Transformer. For example, we put an undefined variable in `Transformer#scaffold_add_line_to_file`
```ruby
def scaffold_add_line_to_file(file, content, hook, options = {})
  puts "Will run"
  foo # Undefined variable
  puts "Won't run"

  file = transform_string(file)
  content = transform_string(content)
  hook = transform_string(hook)
  add_line_to_file(file, content, hook, options)
end
```
<details>
  <summary>We get these logs</summary>

```
> bin/super-scaffold crud Project Team title:text_field --sidebar="ti.ti-world"
Writing './app/controllers/account/projects_controller.rb'.
Fixing Standard Ruby on './app/controllers/account/projects_controller.rb'.
Writing './app/views/account/projects/_index.html.erb'.
Writing './app/views/account/projects/_form.html.erb'.
Writing './app/views/account/projects/_menu_item.html.erb'.
Writing './app/views/account/projects/show.json.jbuilder'.
Writing './app/views/account/projects/index.html.erb'.
Writing './app/views/account/projects/_project.json.jbuilder'.
Writing './app/views/account/projects/index.json.jbuilder'.
Writing './app/views/account/projects/edit.html.erb'.
Writing './app/views/account/projects/show.html.erb'.
Writing './app/views/account/projects/_breadcrumbs.html.erb'.
Writing './app/views/account/projects/new.html.erb'.
Writing './config/locales/en/projects.en.yml'.
Writing './app/controllers/api/v1/projects_endpoint.rb'.
Fixing Standard Ruby on './app/controllers/api/v1/projects_endpoint.rb'.
Writing './test/controllers/api/v1/projects_endpoint_test.rb'.
Fixing Standard Ruby on './test/controllers/api/v1/projects_endpoint_test.rb'.
Writing './app/serializers/api/v1/project_serializer.rb'.
Fixing Standard Ruby on './app/serializers/api/v1/project_serializer.rb'.
Will run
rake aborted!
NameError: undefined local variable or method `foo' for #<Scaffolding::Transformer:0x00007f0b59c592c8 @child="Project", @parent="Team", @parents=["Team"], @namespace="account", @class_names_transformer=#<Scaffolding::ClassNamesTransformer:0x00007f0b59c59110 @child="Project", @parent="Team", @namespace="account">, @cli_options={"sidebar"=>"ti.ti-world"}, @additional_steps=[]>

    foo # Undefined variable
    ^^^
/home/gazayas/work/bt/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:345:in `scaffold_add_line_to_file'
/home/gazayas/work/bt/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:1293:in `scaffold_crud'
/home/gazayas/work/bt/bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb:51:in `run'
/home/gazayas/work/bt/bullet_train-super_scaffolding/lib/scaffolding/script.rb:107:in `<main>'
/home/gazayas/work/bt/bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb:25:in `run'
/home/gazayas/work/bt/bullet_train-super_scaffolding/lib/tasks/bullet_train/super_scaffolding_tasks.rake:10:in `block (2 levels) in <main>'
Tasks: TOP => bullet_train:super_scaffolding
(See full trace by running task with --trace)
```
</details>

## No errors raised in `RoutesFileManipulator`
Here are the same lines in `RoutesFileManipulator#insert_before`

```ruby
def insert_before(new_lines, line_number, options = {})
  puts "Will run"
  foo # Undefined variable
  puts "Won't run"

  options[:indent] ||= false
  before = lines[0..(line_number - 1)]
  new_lines = new_lines.map { |line| (block_manipulator.indentation_of(line_number, lines) + (options[:indent] ? "  " : "") + line).gsub(/\s+$/, "") + "\n" }
  after = lines[line_number..]
  self.lines = before + (options[:prepend_newline] ? ["\n"] : []) + new_lines + after
end
```

<details>
  <summary>Here are the logs</summary>

```
> bin/super-scaffold crud Project Team title:text_field --sidebar="ti.ti-world"
Writing './app/controllers/account/projects_controller.rb'.
Fixing Standard Ruby on './app/controllers/account/projects_controller.rb'.
Writing './app/views/account/projects/_index.html.erb'.
Writing './app/views/account/projects/_form.html.erb'.
Writing './app/views/account/projects/_menu_item.html.erb'.
Writing './app/views/account/projects/show.json.jbuilder'.
Writing './app/views/account/projects/index.html.erb'.
Writing './app/views/account/projects/_project.json.jbuilder'.
Writing './app/views/account/projects/index.json.jbuilder'.
Writing './app/views/account/projects/edit.html.erb'.
Writing './app/views/account/projects/show.html.erb'.
Writing './app/views/account/projects/_breadcrumbs.html.erb'.
Writing './app/views/account/projects/new.html.erb'.
Writing './config/locales/en/projects.en.yml'.
Writing './app/controllers/api/v1/projects_endpoint.rb'.
Fixing Standard Ruby on './app/controllers/api/v1/projects_endpoint.rb'.
Writing './test/controllers/api/v1/projects_endpoint_test.rb'.
Fixing Standard Ruby on './test/controllers/api/v1/projects_endpoint_test.rb'.
Writing './app/serializers/api/v1/project_serializer.rb'.
Fixing Standard Ruby on './app/serializers/api/v1/project_serializer.rb'.
Updating './app/controllers/api/v1/root.rb'.
Updating './test/factories/projects.rb'.
Updating './app/models/team.rb'.
Updating './test/controllers/api/v1/projects_endpoint_test.rb'.
Updating './app/views/account/teams/show.html.erb'.
Updating './app/models/project.rb'.
Updating './app/models/project.rb'.
Updating './app/views/account/projects/_form.html.erb'.
Updating './app/views/account/projects/show.html.erb'.
Updating './app/views/account/projects/_index.html.erb'.
Updating './app/views/account/projects/_index.html.erb'.
Updating './config/locales/en/projects.en.yml'.
Updating './config/locales/en/projects.en.yml'.
Updating './app/controllers/account/projects_controller.rb'.
Updating './app/controllers/api/v1/projects_endpoint.rb'.
Updating './app/views/account/projects/_project.json.jbuilder'.
Updating './app/serializers/api/v1/project_serializer.rb'.
Updating './test/controllers/api/v1/projects_endpoint_test.rb'.
Updating './test/controllers/api/v1/projects_endpoint_test.rb'.
Updating './test/controllers/api/v1/projects_endpoint_test.rb'.
Updating './app/models/project.rb'.
Updating './config/locales/en/projects.en.yml'.
Replacing in './config/locales/en/projects.en.yml'.
Will run
Updating 'config/routes.rb'.
Replacing in './config/locales/en/projects.en.yml'.
Updating './app/views/account/shared/_menu.html.erb'.
Restarting the server so it picks up the new localization .yml file.

1. We weren't able to automatically add your `account` routes for you. In theory this should be very rare, so if you could reach out on Slack, you could probably provide context that will help us fix whatever the problem was. In the meantime, to add the routes manually, we've got a guide at https://blog.bullettrain.co/nested-namespaced-rails-routing-examples/ .

2. If you would like the table view you've just generated to reactively update when a Project is updated on the server, please edit `app/models/team.rb`, locate the `has_many :projects`, and add `enable_updates: true` to it.

```
</details>

You can see that `Will run` shows up near the bottom, but there is no error being raised, `Won't run` never runs, and the process continues as if there's no problem.

**Comment by gazayas** [comment]
I'm thinking it's this block
```ruby
begin
  routes_manipulator.apply([routes_namespace])
rescue
  add_additional_step :yellow, "We weren't able to automatically add your `#{routes_namespace}` routes for you. In theory this should be very rare, so if you could reach out on Slack, you could probably provide context that will help us fix whatever the problem was. In the meantime, to add the routes manually, we've got a guide at https://blog.bullettrain.co/nested-namespaced-rails-routing-examples/ ."
end
```
